parameters:
    riper_security_active_directory_token: Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    #This token is faulty because it does not do one security step. It does not erase the password in order to re-use it.
    riper_security_active_directory_token_faulty : Riper\Security\ActiveDirectoryBundle\Security\Token\FaultyToken

    riper_security_tokens_classes :
        standard : "%riper_security_active_directory_token%"
        faulty : "%riper_security_active_directory_token_faulty%"

services:
    riper.security.active.directory.user.provider:
        class: Riper\Security\ActiveDirectoryBundle\Security\User\AdUserProvider
        arguments: ["%riper.security.active_directory.settings%", "@riper.security.active.directory.service.adldap", "@translator"]

    riper.security.active.directory.authentication.provider:
        class: Riper\Security\ActiveDirectoryBundle\Security\Authentication\AdAuthProvider
        arguments: ["@riper.security.active.directory.user.provider", "", "@riper.security.active.directory.service.adldap", "@translator", "%riper_security_tokens_classes%", "%riper.security.active_directory.settings%" ]

    riper.security.active.directory.service.adldap:
        class: Riper\Security\ActiveDirectoryBundle\Service\AdldapService
        arguments: [ "%riper.security.active_directory.settings%"]

    riper.security.active.directory.factory.adldap:
        class: "Riper\Security\ActiveDirectoryBundle\Security\Factory\AdldapFactory"
        arguments: [ "@security.token_storage", "@riper.security.active.directory.service.adldap" ]
